# Generated by Django 5.0.9 on 2024-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(help_text='Nombre del usuario', max_length=100, unique=True)),
                ('contraseña', models.CharField(help_text='Contraseña del usuario', max_length=128)),
                ('rol', models.CharField(choices=[('1', 'Director de carrera'), ('2', 'Jefe de laboratorio')], help_text='Rol del usuario', max_length=1)),
                ('estado', models.IntegerField(choices=[(1, 'Habilitado'), (0, 'Deshabilitado')], default=1, help_text='Estado del usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
    ]
