# Generated by Django 5.0.9 on 2024-10-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docente', '0003_dircarrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionTecnica',
            fields=[
                ('id_documentacion', models.AutoField(primary_key=True, serialize=False)),
                ('documentacion', models.FileField(help_text='Documentación técnica en formato PDF', upload_to='documentacion_tecnica/')),
            ],
            options={
                'verbose_name': 'Documentación Técnica',
                'verbose_name_plural': 'Documentaciones Técnicas',
                'db_table': 'Documentacion_Tecnica',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_laboratorio', models.CharField(help_text='Nombre del Laboratorio', max_length=15)),
                ('ubicacion', models.CharField(help_text='Ubicación del laboratorio', max_length=100)),
                ('id_jefe_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_lab', to='Docente.jefelaboratorio')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha del comentario')),
                ('estado', models.CharField(choices=[('solucionado', 'Solucionado'), ('no_solucionado', 'No Solucionado')], default='no_solucionado', help_text='Estado del comentario', max_length=20)),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'Comentario',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(help_text='Fecha de mantenimiento')),
                ('descripcion', models.TextField(help_text='Descripción del mantenimiento realizado')),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='Laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'Mantenimiento',
            },
        ),
    ]
