# Generated by Django 5.0.9 on 2024-10-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(help_text='Nombre del equipo', max_length=150)),
                ('modelo', models.CharField(help_text='Modelo del equipo', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción del equipo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del equipo')),
                ('tiempo_de_vida', models.DateTimeField(help_text='Tiempo de vida útil del equipo')),
                ('estado_equipo', models.IntegerField(choices=[(1, 'En uso'), (2, 'Dañado'), (3, 'Mantenimiento'), (4, 'Obsoleto')], default=1, help_text='Estado del equipo')),
                ('id_documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_documentacion', to='Laboratorio.documentaciontecnica')),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='EquipoFungible',
            fields=[
                ('id_fungible', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fungible', models.CharField(help_text='Nombre del equipo fungible', max_length=120)),
                ('descripcion', models.TextField(help_text='Descripción del equipo fungible')),
                ('cantidad', models.IntegerField(help_text='Cantidad disponible')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del equipo fungible')),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_fungibles', to='Laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Equipo Fungible',
                'verbose_name_plural': 'Equipos Fungibles',
                'db_table': 'Equipo_fungible',
            },
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id_mobiliario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mobiliario', models.CharField(help_text='Nombre del mobiliario', max_length=120)),
                ('descripcion', models.TextField(help_text='Descripción del mobiliario')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del mobiliario')),
                ('estado_mobiliario', models.IntegerField(choices=[(1, 'En uso'), (2, 'Obsoleto')], default=1, help_text='Estado del mobiliario')),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiliarios', to='Laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Mobiliario',
                'verbose_name_plural': 'Mobiliarios',
                'db_table': 'Mobiliario',
            },
        ),
    ]
