# Generated by Django 5.0.9 on 2024-10-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0002_equipo_equipofungible_mobiliario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(help_text='Describa su comentario', null=True),
        ),
    ]
