# Generated by Django 5.0.9 on 2024-10-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombres', max_length=75)),
                ('apellido', models.CharField(default='', help_text='Apellidos', max_length=75)),
                ('carnet_identidad', models.BigIntegerField(help_text='Número de carnet de identidad', unique=True)),
                ('correo', models.EmailField(help_text='Correo electrónico', max_length=254, unique=True)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='Usuario.usuario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'Docentes',
            },
        ),
    ]
