# Generated by Django 5.0.9 on 2024-10-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JefeLaboratorio',
            fields=[
                ('id_jefe_lab', models.AutoField(primary_key=True, serialize=False)),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefaturas', to='Docente.docente')),
            ],
            options={
                'verbose_name': 'Jefe de Laboratorio',
                'verbose_name_plural': 'Jefes de Laboratorio',
                'db_table': 'Jefe_laboratorio',
            },
        ),
    ]
