# Generated by Django 5.0.9 on 2024-10-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_jefelaboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirCarrera',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_carrera', to='Docente.docente')),
            ],
            options={
                'verbose_name': 'Director de Carrera',
                'verbose_name_plural': 'Directores de Carrera',
                'db_table': 'Dir_carrera',
            },
        ),
    ]
